name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint — JSDoc comments
        run: npm run lint:comment

      - name: Lint - Code
        run: npm run lint:code

      - name: Format
        run: npm run format:check

      - name: Unit tests with coverage
        run: npm run coverage:lcov

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v6
        with:
          files: ./dist/coverage/coverage.lcov
          report_type: "test_results"
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v6
        with:
          files: ./dist/coverage/tests.xml
          report_type: "test_results"
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Self-link to enable e2e tests of CLI
        run: npm link

      # - name: e2e tests
      #   run: npm run test:e2e
